apiVersion: v1
kind: Service
metadata:
  name: service-client
  labels:
    {{- include "foodadvisor-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "foodadvisor-chart.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
