# Default values for foodadvisor-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Global settings
replicaCount: 1
serviceAccount:
  create: true  # Defina como true para criar uma ServiceAccount
  name: ""      # Deixe vazio para usar o nome padrão
# Backend configuration
backend:
  replicaCount: 1
  image:
    repository: leonardojp1/foodadvisor-api
    pullPolicy: IfNotPresent
    tag: ""
  imagePullSecrets: []
  nameOverride: ""
  fullnameOverride: ""
  serviceAccount:
    create: true
    annotations: {}
    name: ""
  podAnnotations: {}
  podSecurityContext: {}
  securityContext: {}
  service:
    type: ClusterIP
    port: 1337
  ingress:
    enabled: false
    className: ""
    annotations: {}
    hosts:
      - host: chart-example.local
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls: []
  resources: {}
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
  nodeSelector: {}
  tolerations: []
  affinity: {}
  extraEnvs:
    - name: DATABASE_CLIENT
      value: postgres
    - name: DATABASE_HOST
      value: strapi-foodadvisor-postgresql
    - name: DATABASE_PORT
      value: "5432"  # Convertido para string
    - name: DATABASE_USERNAME
      value: strapi
    - name: DATABASE_PASSWORD
      value: strapi
    - name: DATABASE_NAME
      value: strapi

# Frontend configuration
frontend:
  replicaCount: 1
  image:
    repository: leonardojp1/foodadvisor-client
    pullPolicy: IfNotPresent
    tag: ""
  imagePullSecrets: []
  nameOverride: ""
  fullnameOverride: ""
  serviceAccount:
    create: true
    annotations: {}
    name: ""
  podAnnotations: {}
  podSecurityContext: {}
  securityContext: {}
  service:
    type: ClusterIP
    port: 3000
  ingress:
    enabled: false
    className: ""
    annotations: {}
    hosts:
      - host: foodadvisor.frontend
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls: []
  resources: {}
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
  nodeSelector: {}
  tolerations: []
  affinity: {}
  extraEnvs:
    - name: DATABASE_CLIENT
      value: postgres
    - name: DATABASE_HOST
      value: strapi-foodadvisor-postgresql
    - name: DATABASE_PORT
      value: "5432"  # Convertido para string
    - name: DATABASE_USERNAME
      value: strapi
    - name: DATABASE_PASSWORD
      value: strapi
    - name: DATABASE_NAME
      value: strapi


